export { default as recommend } from './__recommend.md'
export { default as demo1 } from './__demo1.md'
export { default as demo2 } from './__demo2.md'
export { default as demo3 } from './__demo3.md'
export { default as api } from './__api.md'
