export { default as recommend } from './__recommend.md'
export { default as primary } from './primary.md'
export { default as auxiliary } from './auxiliary.md'
export { default as neutral } from './neutral.md'
export { default as api } from './__api.md'
export { default as rules } from './rules.md'
